### PR TITLE
Add tests and Makefile, fix typos

### PR DESCRIPTION
**Pull request by marksteward**
Add tests to sanity check JSON, and basic date tests
Add Makefile and .travis.yml
A few trivial formatting changes for flake8 and typos in data
Add missing (object) after class name

### CODE REVIEW

**Comment by jaylett** [comment]
I'm unconvinced that changing to new-style classes counts as fixing a typo ;-)

Without tests I'm not completely comfortable merging this without at least thinking about it for a bit (although it's unlikely we'll hit MRO issues, and we're not using it as a context manager…).

**Comment by marksteward** [comment]
Working on some basic (data validation) tests atm. What tests would you need to merge this?

**Comment by jaylett** [comment]
I think tests of the date range API function would suffice.

**Comment by Jonty** [comment]
I hadn't even noticed I'd forgotten to declare it as a new-style class. Shouldn't be any issues with it though, there's no complex behaviour that requires them.

**Comment by marksteward** [comment]
Added some basic tests for the JSON file and fetching future events, and a Makefile. Is there a neat way to run them on Heroku, or should we set up Travis?

**Comment by Jonty** [comment]
No, heroku doesn't provide it, but they can poll travis for passing tests before deploying.

Travis it is.

**Pull request merged**
